comment fgfdgfdh


max = 020h or 545

comment sdnaslkdnld
;gfd
;gdf
;gdfg
;dfgdfg
;dfg
;df
max = 20


a dd ?
b dd ?
d dd ?
e dd ?
f dd ?
g dd ?
h dd ?
i dd ?
j dd ?
k db ?
l dd ?
asdfd dq ?
dfg dq ?
fd dq ?
hg dq ?
hsdadsdfdsf dq ?
gf dq ?
hf dq ?
gh dq ?
fgh dq ?
fghfg dq ?
sds typedef dword

m struct
n db ?
o db ?
p db ?
q dd ?
r dd ?
m ends 

_z struct
an db ?
ao db ?
spdfdffhg db ?
dad dd ?
dsdds dd ?
_z ends
z typedef _z 
