# Project: julia
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS =  -L"E:/Dev-Cpp/lib" -mwindows wingraph.o libd3d8.a julia.obj  -s 
INCS =  -I"E:/Dev-Cpp/include" 
CXXINCS =  -I"E:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"E:/Dev-Cpp/include/c++/3.4.2/backward"  -I"E:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"E:/Dev-Cpp/include/c++/3.4.2"  -I"E:/Dev-Cpp/include" 
BIN  = julia.exe
CXXFLAGS = $(CXXINCS)   -fverbose-asm -fexpensive-optimizations -O3
CFLAGS = $(INCS) -save-temps   -fverbose-asm -fexpensive-optimizations -O3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before julia.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "julia.exe" $(LIBS)

main.o: main.cpp
	$(CC) -c main.cpp -o main.o $(CFLAGS)
