@echo off
md c:\TRON
cls
echo KOPIOWANIE TEKSTUR
copy TEX1.BMP c:\tron
copy TEX2.BMP c:\tron
copy TEX3.BMP c:\tron
copy TEX4.BMP c:\tron
copy TEX5.BMP c:\tron
copy TEX6.BMP c:\tron
copy TEX7.BMP c:\tron
copy TEX8.BMP c:\tron
copy TEX9.BMP c:\tron
copy TEX10.BMP c:\tron
echo KOPIOWANIE MAP
copy MAP1.MAP	c:\tron
copy MAP2.MAP	c:\tron
copy MAP3.MAP	c:\tron
echo KOPIOWANIE PLIKOW *.EXE
copy TRON.EXE	c:\tron
copy SETUP.EXE	c:\tron
echo KOPIOWANIE PLIKU README I IKONKI
copy README.TXT	c:\tron
copy TRON.ICO	c:\tron